name: CI-Docker

on:
  push:
    branches:
      - main
      - ee-toolchain-gcc10

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ github.repository }}-gcc10:latest
    
    # - name: Send Compile action
    #   run: |
    #     export DISPATCH_ACTION="$(echo run_build)"
    #     echo "NEW_DISPATCH_ACTION=$DISPATCH_ACTION" >> $GITHUB_ENV

    # - name: Repository Dispatch
    #   uses: peter-evans/repository-dispatch@v1
    #   with:
    #     repository: ${{ github.repository_owner }}/ps2toolchain
    #     token: ${{ secrets.DISPATCH_TOKEN }}
    #     event-type: ${{ env.NEW_DISPATCH_ACTION }}